# Generated by Django 2.1.1 on 2018-09-09 02:26

import adli.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='batch name')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['-date'],
                'verbose_name': 'batch',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='book name')),
                ('donate_date', models.DateField(verbose_name='donate date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('collected_amount', models.IntegerField(blank=True, null=True, verbose_name='collected amount')),
                ('control_number', models.IntegerField(blank=True, null=True, verbose_name='control number')),
                ('author_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='author')),
                ('publisher', models.CharField(blank=True, max_length=120, null=True, verbose_name='publisher')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='publish date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('last_modify_date', models.DateField(auto_now_add=True, null=True, verbose_name='last modify date')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zengshu.Batch', verbose_name='batch')),
            ],
            options={
                'verbose_name_plural': 'books',
                'ordering': ['-donate_date'],
                'verbose_name': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='book status name')),
            ],
            options={
                'verbose_name_plural': 'book status',
                'verbose_name': 'book status',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='book type name')),
            ],
            options={
                'verbose_name_plural': 'book types',
                'verbose_name': 'book type',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='donor name')),
                ('name_index', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('donor_type', models.IntegerField(choices=[(0, 'personal'), (1, 'organization')], default=1, verbose_name='donor type')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='contact info')),
            ],
            options={
                'verbose_name_plural': 'donors',
                'verbose_name': 'donor',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='log time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='log content')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zengshu.Book')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='operator')),
            ],
            options={
                'verbose_name_plural': 'logs',
                'ordering': ['-time'],
                'verbose_name': 'log',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='photo name')),
                ('image', models.ImageField(upload_to=adli.utils.wrapper, verbose_name='Image')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'photos',
                'verbose_name': 'photo',
            },
        ),
        migrations.CreateModel(
            name='ZshBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.IntegerField()),
                ('bookname', models.CharField(max_length=60)),
                ('author', models.CharField(blank=True, max_length=60)),
                ('publisher', models.CharField(blank=True, max_length=60)),
                ('public_date', models.CharField(blank=True, max_length=10)),
                ('vols', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('present_name', models.CharField(max_length=60)),
                ('info', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'zsh_book',
            },
        ),
        migrations.CreateModel(
            name='ZshPresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.IntegerField()),
                ('present_name', models.CharField(max_length=60)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('vols', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('contact2', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'zsh_present',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zengshu.BookType', verbose_name='book type'),
        ),
        migrations.AddField(
            model_name='book',
            name='donor',
            field=models.ManyToManyField(blank=True, to='zengshu.Donor', verbose_name='donor'),
        ),
        migrations.AddField(
            model_name='book',
            name='last_modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='last modify by'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zengshu.BookStatus', verbose_name='status'),
        ),
    ]
